List<Map<String, String>> imageList = [
  {"file": "VVG-1.png", "name": "Le Pont de Langlois à Arles aux Lavandières", "categ": "Van Gogh"},
  {"file": "VVG-2.png", "name": "Terrasse de café de nuit", "categ": "Van Gogh"},
  {"file": "VVG-3.png", "name": "Les tournesols", "categ": "Van Gogh"},
  {"file": "VVG-4.png", "name": "Les Iris", "categ": "Van Gogh"},
  {"file": "VVG-5.png", "name": "Champ de blé avec cyprès", "categ": "Van Gogh"},
  {"file": "VVG-6.png", "name": "Chambre de Van Gogh", "categ": "Van Gogh"},
  {"file": "VVG-7.png", "name": "Barques sur la plage aux Saintes-Maries", "categ": "Van Gogh"},
  {"file": "VVG-8.png", "name": "La Meridienne ou La Sieste", "categ": "Van Gogh"},
  {"file": "VVG-9.png", "name": "Crâne d'homme avec cigarette", "categ": "Van Gogh"},
  {"file": "VVG-10.png", "name": "L'église d'Auvers-sur-Oise", "categ": "Van Gogh"},
  {"file": "VVG-11.png", "name": "La chambre à coucher à Arles", "categ": "Van Gogh"},
  {"file": "VVG-12.png", "name": "Chaumes de Cordeville à Auvers-sur-Oise", "categ": "Van Gogh"},
  {"file": "VVG-13.png", "name": "Deux peupliers sur la route des collines", "categ": "Van Gogh"},
  {"file": "VVG-14.png", "name": "Le bon Samaritain (d'après Delacroix)", "categ": "Van Gogh"},
  {"file": "VVG-15.png", "name": "La Pêche au Printemps, Pont de Clichy", "categ": "Van Gogh"},
  {"file": "VVG-16.png", "name": "Farmhouses at sunset", "categ": "Van Gogh"},
  {"file": "VVG-17.png", "name": "La lectrice de roman", "categ": "Van Gogh"},
  {"file": "VVG-18.png", "name": "Camps de Tziganes avec des voitures attelées", "categ": "Van Gogh"},
  {"file": "VVG-19.png", "name": "Le Faucheur", "categ": "Van Gogh"},
  {"file": "VVG-20.png", "name": "Maisons à Auvers", "categ": "Van Gogh"},
  {"file": "VVG-21.png", "name": "Les meules de foin", "categ": "Van Gogh"},
  {"file": "VVG-22.png", "name": "Portrait du Dr. Gachet", "categ": "Van Gogh"},
  {"file": "VVG-23.png", "name": "Portrait du facteur Joseph Roulin", "categ": "Van Gogh"},
  {"file": "VVG-24.png", "name": "Le peintre sur le chemin de travail", "categ": "Van Gogh"},
  {"file": "VVG-25.png", "name": "Auto-portrait avec oreille bandée et pipe", "categ": "Van Gogh"},

];
